import Head from 'next/head'
import useSWR from 'swr'
import Headlines from '../components/Headlines';
import Footer from '../components/Footer';

export default function Home() {


function PlayerNews() {
  const fetcher = (url) => fetch(url).then((r) => r.json())
  const API = process.env.NEXT_PUBLIC_API
  const { data: news, error } = useSWR(API, fetcher)
  if (error) return <div>failed to load from {API}</div>
  if (!news) return <div>loading...</div>
  return <Headlines data={news} />
}

  return (
    <div>
      <Head>
        <title>NFL Headlines</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 style={{position:'absolute', left:'-999em'}}>NFL Headlines</h1>
        <PlayerNews />
      </main>
      <Footer />
    </div>
  )
}
